[package]
name = "timber"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
platform-dirs = "0.3.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }
time = "0.3.41"
